name: Build MacOS Binary
on:
  push:
    branches:
      - master
  
jobs:
  build:
    name: Build
    runs-on: macos-11.0
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: go build -o build/lemenuaide "github.com/arunura/lemenuaide"
        
        
