name: Build MacOS Binary
on:
  push:
    branches:
      - master
  
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Build MacOS AMD64 binary (Intel CPUs)
        run: GOOS=darwin GOARCH=amd64 go build -o build/lemenuaide-macos-amd64
        
      - name: Build MacOS ARM64 binary (Apple Silicon)
        run: GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 CC=clang go build -o build/lemenuaide-macos-arm64
        
      - name: Create universal binary (fat binary for MacOS)
        run: lipo build/lemenuaide-macos-amd64 build/lemenuaide-macos-arm64 -create -output build/lemenuaide-macos-universal
      
      - name: Assemble application bundle
        run: cp -R -f bundle_macos/* build/LeMenuAide.app/ ; cp -R -f build/lemenuaide-macos-universal build/LeMenuAide.app/Contents/MacOS/

      - name: Print environment info
        run: ls -la ; ls -laR build 
        
        
